version: "3"
services:
    beer-service:
        container_name: beer-service
        image: sebchevre/beer-service:1.2.0
        ports:
         - "9999:80"
         
    mongoapi:
    image: "sebchevre/mongoapi:1.5"
    ports:
      - "9998:80"
      - "9999:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - MONGODB_URL=mongodb://mongodb:27017 
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=9999 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=110978 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mongoapi.pfx 
      - PIPEDREAM_URL=https://31301cce0d381d6c9338a006d3d31044.m.pipedream.net
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/ 
  mongodb:
    container_name: mongodb
    image: "mongo"
    ports: 
      - "27017:27017"
